linters:
  enable-all: true
  disable:
    - forbidigo
    - intrange
    - depguard
    - exhaustruct
    - paralleltest
    - execinquery # Deprecated
    - deadcode # Deprecated
    - exhaustivestruct # Deprecated
    - golint # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - maligned # Deprecated
    - gomnd # Deprecated
    - nosnakecase # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - varcheck # Deprecated
    - gochecknoinits
    - mnd
    - err113
    - gocognit
    - cyclop
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  varnamelen:
    min-name-length: 2
  funlen:
    lines: 160
  lll:
    line-length: 160
  wrapcheck:
    ignorePackageGlobs:
      - encoding/*
      - strconv
      - github.com/pocketbase/*
  gci:
    custom-order: true
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
